version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:stable
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
